const cuisineTypes: string[] = [
  "🇮🇹 Italian",
  "🇲🇽 Mexican",
  "🇨🇳 Chinese",
  "🇮🇳 Indian",
  "🇹🇭 Thai",
  "🇯🇵 Japanese",
  "🇫🇷 French",
  "🇬🇷 Mediterranean",
  "🇬🇷 Greek",
  "🇪🇸 Spanish",
  "🇰🇷 Korean",
  "🇻🇳 Vietnamese",
  "🇱🇧 Lebanese",
  "🇹🇷 Turkish",
  "🇧🇷 Brazilian",
  "🇺🇸 American",
  "🇬🇧 British",
  "🇮🇪 Irish",
  "🇩🇪 German",
  "🇿🇦 African",
  "🇯🇲 Caribbean",
  "🇸🇦 Middle Eastern",
  "🇦🇺 Australian",
  "🇳🇿 New Zealand",
  "🇨🇦 Canadian",
  "🇿🇦 South African",
  "🇵🇹 Portuguese",
  "🇷🇺 Russian",
  "🇨🇿 Czech",
  "🇵🇱 Polish",
  "🇭🇺 Hungarian",
  "🇫🇮 Finnish",
  "🇳🇴 Norwegian",
  "🇩🇰 Danish",
  "🇸🇪 Swedish",
  "🇮🇸 Icelandic",
  "🇨🇭 Swiss",
  "🇦🇹 Austrian",
  "🇧🇪 Belgian",
  "🇳🇱 Dutch",
  "🇱🇺 Luxembourgish",
  "🇸🇰 Slovak",
  "🇸🇮 Slovenian",
  "🇭🇷 Croatian",
  "🇷🇸 Serbian",
  "🇧🇦 Bosnian",
  "🇲🇪 Montenegrin",
  "🇦🇱 Albanian",
  "🇽🇰 Kosovan",
  "🇲🇰 Macedonian",
  "🇧🇬 Bulgarian",
  "🇷🇴 Romanian",
  "🇲🇩 Moldovan",
  "🇺🇦 Ukrainian",
  "🇧🇾 Belarusian",
  "🇱🇹 Lithuanian",
  "🇱🇻 Latvian",
  "🇪🇪 Estonian",
  "🇲🇹 Maltese",
  "🇨🇾 Cypriot",
  "🇬🇮 Gibraltarian",
];

export { cuisineTypes };
