const dietTypes: string[] = [
  "Gluten Free",
  "Ketogenic",
  "Vegetarian",
  "Vegan",
  "Pescatarian",
  "Paleo",
  "Low FODMAP",
  "Whole30",
  "Dairy Free",
  "Low Carb",
  "Diabetic",
  "Low Fat",
  "High Protein",
  "Lacto Vegetarian",
  "Ovo Vegetarian",
  "Lacto-Ovo Vegetarian",
  "Raw Vegan",
  "Primal",
  "Flexitarian",
  "DASH Diet",
  "Anti-Inflammatory",
  "Carnivore",
  "No Sugar",
  "Plant-Based",
  "Low Sodium",
];

export { dietTypes };
