const dislikedIngredientTypes = [
  { id: 1, name: "Avocado" },
  { id: 2, name: "Banana" },
  { id: 3, name: "Beef" },
  { id: 4, name: "Bell pepper" },
  { id: 5, name: "Black beans" },
  { id: 6, name: "Broccoli" },
  { id: 7, name: "Carrot" },
  { id: 8, name: "Celery" },
  { id: 9, name: "Chicken" },
  { id: 10, name: "Chickpeas" },
  { id: 11, name: "Cilantro" },
  { id: 12, name: "Coconut" },
  { id: 13, name: "Corn" },
  { id: 14, name: "Cucumber" },
  { id: 15, name: "Egg" },
  { id: 16, name: "Fish" },
  { id: 17, name: "Garlic" },
  { id: 18, name: "Ginger" },
  { id: 19, name: "Green beans" },
  { id: 20, name: "Kale" },
  { id: 21, name: "Lemon" },
  { id: 22, name: "Lime" },
  { id: 23, name: "Mushroom" },
  { id: 24, name: "Olive" },
  { id: 25, name: "Onion" },
  { id: 26, name: "Pasta" },
  { id: 27, name: "Peanut" },
  { id: 28, name: "Peas" },
  { id: 29, name: "Pork" },
  { id: 30, name: "Potato" },
  { id: 31, name: "Pumpkin" },
  { id: 32, name: "Quinoa" },
  { id: 33, name: "Rice" },
  { id: 34, name: "Salmon" },
  { id: 35, name: "Shrimp" },
  { id: 36, name: "Spinach" },
  { id: 37, name: "Squash" },
  { id: 38, name: "Sweet potato" },
  { id: 39, name: "Tofu" },
  { id: 40, name: "Tomato" },
  { id: 41, name: "Turkey" },
  { id: 42, name: "Zucchini" },
];

export { dislikedIngredientTypes };
