const cuisineTypes = [
  { id: 1, name: "🇮🇹 Italian" },
  { id: 2, name: "🇲🇽 Mexican" },
  { id: 3, name: "🇨🇳 Chinese" },
  { id: 4, name: "🇮🇳 Indian" },
  { id: 5, name: "🇹🇭 Thai" },
  { id: 6, name: "🇯🇵 Japanese" },
  { id: 7, name: "🇫🇷 French" },
  { id: 8, name: "🇬🇷 Mediterranean" },
  { id: 9, name: "🇬🇷 Greek" },
  { id: 10, name: "🇪🇸 Spanish" },
  { id: 11, name: "🇰🇷 Korean" },
  { id: 12, name: "🇻🇳 Vietnamese" },
  { id: 13, name: "🇱🇧 Lebanese" },
  { id: 14, name: "🇹🇷 Turkish" },
  { id: 15, name: "🇧🇷 Brazilian" },
  { id: 16, name: "🇺🇸 American" },
  { id: 17, name: "🇬🇧 British" },
  { id: 18, name: "🇮🇪 Irish" },
  { id: 19, name: "🇩🇪 German" },
  { id: 20, name: "🇿🇦 African" },
  { id: 21, name: "🇯🇲 Caribbean" },
  { id: 22, name: "🇸🇦 Middle Eastern" },
  { id: 25, name: "🇦🇺 Australian" },
  { id: 26, name: "🇳🇿 New Zealand" },
  { id: 27, name: "🇨🇦 Canadian" },
  { id: 34, name: "🇿🇦 South African" },
  { id: 35, name: "🇵🇹 Portuguese" },
  { id: 36, name: "🇷🇺 Russian" },
  { id: 37, name: "🇨🇿 Czech" },
  { id: 38, name: "🇵🇱 Polish" },
  { id: 39, name: "🇭🇺 Hungarian" },
  { id: 40, name: "🇫🇮 Finnish" },
  { id: 41, name: "🇳🇴 Norwegian" },
  { id: 42, name: "🇩🇰 Danish" },
  { id: 43, name: "🇸🇪 Swedish" },
  { id: 44, name: "🇮🇸 Icelandic" },
  { id: 45, name: "🇨🇭 Swiss" },
  { id: 46, name: "🇦🇹 Austrian" },
  { id: 47, name: "🇧🇪 Belgian" },
  { id: 48, name: "🇳🇱 Dutch" },
  { id: 49, name: "🇱🇺 Luxembourgish" },
  { id: 50, name: "🇸🇰 Slovak" },
  { id: 51, name: "🇸🇮 Slovenian" },
  { id: 52, name: "🇭🇷 Croatian" },
  { id: 53, name: "🇷🇸 Serbian" },
  { id: 54, name: "🇧🇦 Bosnian" },
  { id: 55, name: "🇲🇪 Montenegrin" },
  { id: 56, name: "🇦🇱 Albanian" },
  { id: 57, name: "🇽🇰 Kosovan" },
  { id: 58, name: "🇲🇰 Macedonian" },
  { id: 59, name: "🇧🇬 Bulgarian" },
  { id: 60, name: "🇷🇴 Romanian" },
  { id: 61, name: "🇲🇩 Moldovan" },
  { id: 62, name: "🇺🇦 Ukrainian" },
  { id: 63, name: "🇧🇾 Belarusian" },
  { id: 64, name: "🇱🇹 Lithuanian" },
  { id: 65, name: "🇱🇻 Latvian" },
  { id: 66, name: "🇪🇪 Estonian" },
  { id: 67, name: "🇲🇹 Maltese" },
  { id: 68, name: "🇨🇾 Cypriot" },
  { id: 69, name: "🇬🇮 Gibraltarian" },
];

export { cuisineTypes };
