import { Dimensions } from "react-native";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
const NAVIGATION_BOTTOM_TABS_HEIGHT = 58;
const BUTTON_HEIGHT_SMALL = 40;
const BUTTON_HEIGHT_MEDIUM = 48;
const BUTTON_HEIGHT_LARGE = 58;
const ICON_SIZE_SMALL = 24;
const ICON_SIZE_MEDIUM = 28;
const ICON_SIZE_LARGE = 32;
const BORDER_RADIUS_SMALL = 12;
const BORDER_RADIUS_MEDIUM = 24;
const BORDER_RADIUS_LARGE = 36;
export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  NAVIGATION_BOTTOM_TABS_HEIGHT,
  BUTTON_HEIGHT_SMALL,
  BUTTON_HEIGHT_MEDIUM,
  BUTTON_HEIGHT_LARGE,
  ICON_SIZE_SMALL,
  ICON_SIZE_MEDIUM,
  ICON_SIZE_LARGE,
  BORDER_RADIUS_SMALL,
  BORDER_RADIUS_MEDIUM,
  BORDER_RADIUS_LARGE,
};
