import { GroceryItemCategoryType } from "@/models/GroceryItemCategoryType";

const groceryItemCategoryTypes: GroceryItemCategoryType[] = [
  {
    name: "Fruit",
    items: [
      "Apple",
      "Banana",
      "Orange",
      "Strawberry",
      "Grapes",
      "Mango",
      "Blueberry",
      "Peach",
      "Pineapple",
      "Watermelon",
    ],
  },
  {
    name: "Vegetable",
    items: [
      "Carrot",
      "Potato",
      "Tomato",
      "Onion",
      "Lettuce",
      "Broccoli",
      "Spinach",
      "Cucumber",
      "Bell Pepper",
      "Cauliflower",
    ],
  },
  {
    name: "Dairy",
    items: [
      "Milk",
      "Cheese",
      "Yogurt",
      "Butter",
      "Cream",
      "Cottage Cheese",
      "Sour Cream",
      "Ice Cream",
    ],
  },
  {
    name: "Grain",
    items: [
      "Bread",
      "Rice",
      "Pasta",
      "Oats",
      "Cereal",
      "Quinoa",
      "Barley",
      "Cornmeal",
    ],
  },
  {
    name: "Protein",
    items: [
      "Chicken",
      "Beef",
      "Pork",
      "Fish",
      "Eggs",
      "Tofu",
      "Beans",
      "Lentils",
      "Nuts",
      "Turkey",
    ],
  },
  {
    name: "Beverages",
    items: [
      "Water",
      "Juice",
      "Soda",
      "Coffee",
      "Tea",
      "Beer",
      "Wine",
      "Milk",
      "Smoothie",
    ],
  },
  {
    name: "Bakery",
    items: [
      "Bread",
      "Bagel",
      "Croissant",
      "Muffin",
      "Cake",
      "Cookie",
      "Pie",
      "Doughnut",
    ],
  },
  {
    name: "Frozen",
    items: [
      "Frozen Pizza",
      "Ice Cream",
      "Frozen Vegetables",
      "Frozen Fruit",
      "Frozen Meals",
      "Frozen Desserts",
    ],
  },
  {
    name: "Snacks",
    items: [
      "Chips",
      "Crackers",
      "Popcorn",
      "Pretzels",
      "Nuts",
      "Granola Bars",
      "Chocolate",
      "Candy",
    ],
  },
  {
    name: "Condiments",
    items: [
      "Ketchup",
      "Mustard",
      "Mayonnaise",
      "Soy Sauce",
      "Hot Sauce",
      "Salad Dressing",
      "BBQ Sauce",
      "Vinegar",
    ],
  },
  {
    name: "Canned Goods",
    items: [
      "Canned Beans",
      "Canned Tomatoes",
      "Canned Soup",
      "Canned Fish",
      "Canned Vegetables",
      "Canned Fruit",
    ],
  },
  {
    name: "Spices and Herbs",
    items: [
      "Salt",
      "Pepper",
      "Garlic Powder",
      "Onion Powder",
      "Paprika",
      "Cumin",
      "Basil",
      "Oregano",
      "Thyme",
      "Cinnamon",
    ],
  },
  {
    name: "Baking Supplies",
    items: [
      "Flour",
      "Sugar",
      "Baking Soda",
      "Baking Powder",
      "Yeast",
      "Chocolate Chips",
      "Vanilla Extract",
      "Cocoa Powder",
    ],
  },
  {
    name: "Household",
    items: [
      "Paper Towels",
      "Toilet Paper",
      "Laundry Detergent",
      "Dish Soap",
      "Garbage Bags",
      "Aluminum Foil",
      "Plastic Wrap",
    ],
  },
  {
    name: "Personal Care",
    items: [
      "Shampoo",
      "Conditioner",
      "Soap",
      "Toothpaste",
      "Deodorant",
      "Lotion",
      "Shaving Cream",
      "Toothbrush",
    ],
  },
  {
    name: "Baby Products",
    items: [
      "Diapers",
      "Baby Wipes",
      "Baby Food",
      "Baby Formula",
      "Baby Lotion",
      "Baby Shampoo",
      "Baby Powder",
    ],
  },
  {
    name: "Pet Supplies",
    items: [
      "Dog Food",
      "Cat Food",
      "Bird Seed",
      "Fish Food",
      "Pet Treats",
      "Pet Toys",
      "Cat Litter",
      "Pet Shampoo",
    ],
  },
];

export default groceryItemCategoryTypes;
